# Generated by Django 3.2.7 on 2022-01-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='due',
        ),
        migrations.RemoveField(
            model_name='item',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='remainingtime',
        ),
        migrations.RemoveField(
            model_name='item',
            name='startdate',
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.TextField(),
        ),
    ]
